=== Dmitriy141004/Grid-Stepper/build/last/resources/levels/level-pack-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="cellType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="wall" />
            <xs:enumeration value="empty" />
            <xs:enumeration value="start" />
            <xs:enumeration value="finish" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="direction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="up"/>
            <xs:enumeration value="down"/>
            <xs:enumeration value="left"/>
            <xs:enumeration value="right"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="levelNumber">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="level-pack">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="level" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="game-field" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="column" maxOccurs="unbounded" minOccurs="1">
                                            <xs:complexType>
                                                <xs:choice maxOccurs="unbounded" minOccurs="1">
                                                    <xs:element name="wall"/>
                                                    <xs:element name="empty"/>
                                                    <xs:element name="finish"/>
                                                    <xs:element name="start"/>
                                                    <xs:element name="optional"/>
                                                    <xs:element name="direction-pad">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="pass-direct" use="required" type="direction"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="bridge"/>
                                                    <xs:element name="background"/>
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                        <xs:attribute type="levelNumber" name="number" use="required" />
                        <xs:attribute type="xs:boolean" name="completed" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <xs:attribute type="xs:string" name="name" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Dmitriy141004/Grid-Stepper/build/last/resources/levels/classic.xml
<?xml version="1.0" encoding="UTF-8" ?>

<level-pack name="Classic" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="level-pack-schema.xsd">
    <level number="1" completed="false">
        <game-field>
            <column>
                <empty />
                <empty />
            </column>
            <column>
                <finish />
                <start  />
            </column>
        </game-field>
    </level>

    <level number="2" completed="false">
        <game-field>
            <column>
                <empty />
                <empty />
                <empty />
            </column>
            <column>
                <empty />
                <wall  />
                <empty />
            </column>
            <column>
                <start  />
                <finish />
                <empty  />
            </column>
        </game-field>
    </level>

    <level number="3" completed="false">
        <game-field>
            <column>
                <wall   />
                <empty  />
                <empty  />
            </column>
            <column>
                <empty  />
                <empty  />
                <empty  />
            </column>
            <column>
                <start  />
                <wall   />
                <finish />
            </column>
        </game-field>
    </level>

    <level number="4" completed="false">
        <game-field>
            <column>
                <empty  />
                <empty  />
                <wall   />
                <wall   />
            </column>
            <column>
                <empty  />
                <empty  />
                <empty  />
                <empty  />
            </column>
            <column>
                <empty  />
                <wall   />
                <wall   />
                <empty  />
            </column>
            <column>
                <start  />
                <finish />
                <empty  />
                <empty  />
            </column>
        </game-field>
    </level>

    <level number="5" completed="false">
        <game-field>
            <column>
                <wall   />
                <empty  />
                <empty  />
                <empty  />
                <start  />
            </column>
            <column>
                <empty  />
                <empty  />
                <empty  />
                <empty  />
                <wall   />
            </column>
            <column>
                <empty  />
                <wall   />
                <empty  />
                <empty  />
                <empty  />
            </column>
            <column>
                <empty  />
                <empty  />
                <empty  />
                <wall   />
                <empty  />
            </column>
            <column>
                <empty  />
                <empty  />
                <wall   />
                <finish />
                <empty  />
            </column>
        </game-field>
    </level>
</level-pack>

=== Dmitriy141004/Grid-Stepper/deploy/input/opt/Grid-Stepper-Game/resources/levels/classic.xml
<?xml version="1.0" encoding="UTF-8" ?>

<level-pack name="classic" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="level-pack-schema.xsd">
    <level name="first steps" number="1">
        <game-field>
            <column>
                <wall   />
                <empty  />
                <empty  />
            </column>
            <column>
                <empty  />
                <empty  />
                <empty  />
            </column>
            <column>
                <start  />
                <wall   />
                <finish />
            </column>
        </game-field>
    </level>

    <level name="err..." number="2">
        <game-field>
            <column>
                <wall  />
                <empty />
                <empty />
                <empty />
                <start />
            </column>
            <column>
                <empty  />
                <empty  />
                <empty  />
                <empty  />
                <wall   />
            </column>
            <column>
                <empty  />
                <wall   />
                <empty  />
                <empty  />
                <empty  />
            </column>
            <column>
                <empty  />
                <empty  />
                <empty  />
                <wall   />
                <empty  />
            </column>
            <column>
                <empty  />
                <empty  />
                <wall   />
                <finish />
                <empty  />
            </column>
        </game-field>
    </level>
</level-pack>
