=== Dmitriy141004/Grid-Stepper/resources/levels/level-pack-schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="cellType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="wall" />
            <xs:enumeration value="empty" />
            <xs:enumeration value="start" />
            <xs:enumeration value="finish" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="level-pack">
        <xs:annotation>
            <xs:documentation>
                <h1>Documentation for tag</h1>

                <table>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                    <tr>
                        <td>Short description</td>
                        <td>Root element for level pack</td>
                    </tr>
                    <tr>
                        <td>Tag name</td>
                        <td>level-pack</td>
                    </tr>
                    <tr>
                        <td>Max count</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Min count</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Attributes</td>
                        <td>
                            <ol>
                                <li>&#x00AB;<code>name</code>&#x00BB; - string, must-have</li>
                            </ol>
                        </td>
                    </tr>
                </table>
            </xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:element name="level" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            <h1>Documentation for tag</h1>

                            <table>
                                <tr>
                                    <th>Name</th>
                                    <th>Value</th>
                                </tr>
                                <tr>
                                    <td>Short description</td>
                                    <td>Root element for each level</td>
                                </tr>
                                <tr>
                                    <td>Tag name</td>
                                    <td>level</td>
                                </tr>
                                <tr>
                                    <td>Max count</td>
                                    <td>&#x221E;</td>
                                </tr>
                                <tr>
                                    <td>Min count</td>
                                    <td>0</td>
                                </tr>
                                <tr>
                                    <td>Attributes</td>
                                    <td>
                                        <ol>
                                            <li>&#x00AB;<code>id</code>&#x00BB; - string, must-have</li>
                                            <li>&#x00AB;<code>completed</code>&#x00BB; - boolean, must-have</li>
                                        </ol>
                                    </td>
                                </tr>
                            </table>
                        </xs:documentation>
                    </xs:annotation>

                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="game-field" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation>
                                        <h1>Documentation for tag</h1>

                                        <table>
                                            <tr>
                                                <th>Name</th>
                                                <th>Value</th>
                                            </tr>
                                            <tr>
                                                <td>Short description</td>
                                                <td>Root element for storing game field</td>
                                            </tr>
                                            <tr>
                                                <td>Tag name</td>
                                                <td>game-field</td>
                                            </tr>
                                            <tr>
                                                <td>Max count</td>
                                                <td>1</td>
                                            </tr>
                                            <tr>
                                                <td>Min count</td>
                                                <td>1</td>
                                            </tr>
                                            <tr>
                                                <td>Attributes</td>
                                                <td>None</td>
                                            </tr>
                                        </table>
                                    </xs:documentation>
                                </xs:annotation>

                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="column" maxOccurs="unbounded" minOccurs="1">
                                            <xs:annotation>
                                                <xs:documentation>
                                                    <h1>Documentation for tag</h1>

                                                    <table>
                                                        <tr>
                                                            <th>Name</th>
                                                            <th>Value</th>
                                                        </tr>
                                                        <tr>
                                                            <td>Short description</td>
                                                            <td>Element for storing <b>1</b> column of cells</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Tag name</td>
                                                            <td>grid</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Max count</td>
                                                            <td>&#x221E;</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Min count</td>
                                                            <td>1</td>
                                                        </tr>
                                                        <tr>
                                                            <td>Attributes</td>
                                                            <td>None</td>
                                                        </tr>
                                                    </table>
                                                </xs:documentation>
                                            </xs:annotation>

                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cell" maxOccurs="unbounded" minOccurs="1">
                                                        <xs:annotation>
                                                            <xs:documentation>
                                                                <h1>Documentation for tag</h1>

                                                                <table>
                                                                    <tr>
                                                                        <th>Name</th>
                                                                        <th>cell</th>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Short description</td>
                                                                        <td>Element for storing <b>1</b> cell</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Tag name</td>
                                                                        <td>grid</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Max count</td>
                                                                        <td>&#x221E;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Min count</td>
                                                                        <td>1</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Attributes</td>
                                                                        <td>
                                                                            <ol>
                                                                                <li>&#x00AB;<code>type</code>&#x00BB; - string from enum, must-have</li>
                                                                            </ol>
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </xs:documentation>
                                                        </xs:annotation>

                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute type="cellType" name="type" use="required" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                        <xs:attribute type="xs:string" name="id" use="required" />
                        <xs:attribute type="xs:boolean" name="completed" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <xs:attribute type="xs:string" name="name" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Dmitriy141004/Grid-Stepper/build/jar/resources/levels/classic.xml
<?xml version="1.0" encoding="UTF-8" ?>

<level-pack name="classic" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="level-pack-schema.xsd">

    <level id="1" completed="false">
        <game-field>
            <column>
                <cell type="wall" />
                <cell type="empty" />
                <cell type="empty" />
                <cell type="empty" />
                <cell type="start" />
            </column>
            <column>
                <cell type="empty" />
                <cell type="empty" />
                <cell type="empty" />
                <cell type="empty" />
                <cell type="wall" />
            </column>
            <column>
                <cell type="empty" />
                <cell type="wall" />
                <cell type="empty" />
                <cell type="empty" />
                <cell type="empty" />
            </column>
            <column>
                <cell type="empty" />
                <cell type="empty" />
                <cell type="empty" />
                <cell type="wall" />
                <cell type="empty" />
            </column>
            <column>
                <cell type="empty" />
                <cell type="empty" />
                <cell type="wall" />
                <cell type="finish" />
                <cell type="empty" />
            </column>
        </game-field>
    </level>
</level-pack>
